---
name: Feature Request
description:
  Let us know of a feature or request
body:
  - type: textarea
    id: cadeft-version
    attributes:
      label: cadeft Version
      description: What version of cadeft are you using?
    validations:
      required: true

  - type: textarea
    id: intention
    attributes:
      label: What were you trying to do?
      description: >
        Describe how you were using the cadeft library. Include code samples,
        errors, and stacktraces if appropriate.
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: What did you expect to see?
      description: >
        A short description on how you expect the code to behave.
    validations:
      required: true
